#!/usr/bin/ruby

#######################################################################
## Copyright (c) 2014 ENEO Tecnología S.L.
## This file is part of redBorder.
## redBorder is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## redBorder is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License License for more details.
## You should have received a copy of the GNU Affero General Public License License
## along with redBorder. If not, see <http://www.gnu.org/licenses/>.
########################################################################

require 'rubygems'
require 'chef'
require 'json'

Chef::Config.from_file("/etc/chef/client.rb")
Chef::Config[:node_name]  = "admin"
Chef::Config[:client_key] = "/etc/chef-server/admin.pem"
Chef::Config[:http_retry_count] = 5

role = Chef::Role.load("manager")

if !role.nil?
  ARGV.each do|f|
    printf("Reading #{f}\n")
    if File.exist?(f)
      file = File.read(f)
      hash = JSON.parse(file)
      hash.each do |k,v|
        printf("  * Role key: #{k}\n")
        role.override_attributes[k] = {} if role.override_attributes[k].nil?
        role.override_attributes[k]=role.override_attributes[k].merge(v)
      end
    end
  end
  if role.save
    printf("Role #{role.name} saved successfully\n")
  else
    printf("Role #{role.name} has not been saved!!!!\n")
  end
end

